% clear;
clc;
% % configuracao = mfile();
% % dado = mgenerate(configuracao);
% % network = mnetcreate(dado);
% % network = mnettrain(network,dado);
% otimizacao = [];
% resultado = [];
nome_save = 'rede';
% msave;
mload;
%op_exportar_net([],[],network,dado,'resultado\Redes Neurais\');
nome_save = 'caso1';
otimizacao = motmcreate(configuracao,dado);
otimizacao.distacia = 195.3/1.852;
otimizacao = motmnet(otimizacao,network);
resultado = motmexe(configuracao,dado,network,otimizacao,['resultado\',nome_save,'\ga']);
op_exportar([],[],resultado,resultado.dado,resultado.tipo,['resultado\',nome_save,'\']);
msave;
nome_save = 'caso2';
otimizacao = motmcreate(configuracao,dado);
otimizacao.distacia = 433.75/1.852;
otimizacao = motmnet(otimizacao,network);
resultado = motmexe(configuracao,dado,network,otimizacao,['resultado\',nome_save,'\ga']);
op_exportar([],[],resultado,resultado.dado,resultado.tipo,['resultado\',nome_save,'\']);
msave;
nome_save = 'caso3';
otimizacao = motmcreate(configuracao,dado);
otimizacao.distacia = 440.98/1.852;
otimizacao = motmnet(otimizacao,network);
resultado = motmexe(configuracao,dado,network,otimizacao,['resultado\',nome_save,'\ga']);
op_exportar([],[],resultado,resultado.dado,resultado.tipo,['resultado\',nome_save,'\']);
msave;