function h = plot_2d_barco_fun( resultado,otimizacao )
h = {};
h{1} = figure;
hold on
plot(resultado.plot.value2dx,resultado.plot.output2d);
plot(resultado.ga.x,resultado.ga.fval,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',10,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor','r');
plot(resultado.swarm.x,resultado.swarm.fval,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',7,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor','g');
plot(resultado.sa.x,resultado.sa.fval,...
    'LineStyle','none',...
    'Marker','o',...
    'MarkerSize',4,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor','b');
hold off
grid on;
title(sprintf('Otimização na Função'));
xlabel('Velocidade (km/h)');
ylabel('Consumo (L)');
legend({sprintf('Saída (D: %0.2f nmi)',otimizacao.distacia)
    sprintf('GA (V: %0.2f km/h; C: %0.2f L)',resultado.ga.x,resultado.ga.fval)
    sprintf('PSO (V: %0.2f km/h; C: %0.2f L)',resultado.swarm.x,resultado.swarm.fval)
    sprintf('SA (V: %0.2f km/h; C: %0.2f L)',resultado.sa.x,resultado.sa.fval)});
h{1}.Name = sprintf('Função');
h{1}.NumberTitle = 'off';


end

