clc;
fprintf('Carregando...\n');
load(['save\' nome_save '-configuracao']);
fprintf('Load => configuracao\n');
load(['save\' nome_save '-dado']);
fprintf('Load => dado\n');
load(['save\' nome_save '-network']);
fprintf('Load => network\n');
load(['save\' nome_save '-otimizacao']);
fprintf('Load => otimizacao\n');
load(['save\' nome_save '-resultado']);
fprintf('Load => resultado\n');